# These are supported funding model platforms

custom: ["https://www.paypal.com/donate?token=he5P_2-Ws_Rk_UbjYDvfj_ytFqKJOHi_RavGwif03-2IPLFpvkQuIn3Mv2gIsIg9PnKN91SY8N5ic8CK&locale.x=CY", "https://github.com/sponsors/Furtif"]
github: [cedricp, Furtif]
