# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python App

on:
  push:
    branches: [ master, pyqt5_mode, pyside2 ]
  pull_request:
    branches: [ master, pyqt5_mode, pyside2 ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        versions: [1.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run build of version ${{ matrix.versions }}
      run: |
        # Install dependencies...
        # python -m venv ./venv
        # venv\scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python ddt4all.py -git_test
        #venv\scripts\deactivate
